services:
    quicc:
      build: .
      networks:
        - quicc
      ports:
        - "4433"
      command: >
        python3 -u http3_cc_server.py
        --certificate aioquic/tests/ssl_cert.pem
        --private-key aioquic/tests/ssl_key.pem
        --cc-private-key server_key.pem
    client:
      build: .
      networks:
        - quicc
      command: >
        python3 http3_cc_client.py 
        --ca-certs aioquic/tests/pycacert.pem
        --message "QuiCC can never be detected!"
        --cid-size 8
        --cc-private-key client_key.pem
        --cc-server-public-key
        server_public_key.pem wss://quicc:4433/ws
      logging:
        driver: none

networks:
  quicc:
